name: atv

on:
  schedule:
    - cron: '8 */20 * * *'  # Her 20 saatte bir çalışır, dakikayı değiştirebilirsin
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "atv@bot.com"
          git config --global user.name "atv bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlink

      - name: Run script
        run: python3 ressources/tur/atv.py

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add ressources/tur/atv.m3u8
          git commit -m "atv updated" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
