name: kontv

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "kontv@bot.com"
          git config --global user.name "kontv bot"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run kontv.py
        run: python ressources/tur/kontv.py

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add ressources/tur/kontv.m3u8
          git commit -m "Update kontv.m3u8" || echo "No changes"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
