name: ntvtr

on:
  schedule:
    - cron: '16 */20 * * *' # 20 saatte bir çalıştırmak için
    # - cron: '16 */2 * * *' # 2 saatte bir çalıştırmak için
    # - cron: '*/40 * * * *' # 40 dakikada bir çalıştırmak için yani 00:40, 01:20, 02:00 gibi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "ntvtr@bot.com"
          git config --global user.name "ntvtr bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python3 ressources/tur/ntv.py

      - name: Commit and Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # TOKEN BURADA DEĞİŞTİRİLDİ
        run: |
          git add ressources/tur/*.m3u8
          git commit -m "ntvtr updated" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
