name: ntvtr

on:
  schedule:
    - cron: '16 */20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "ntvtr bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Execute Python script
        run: python3 ressources/tur/ntv.py

      - name: Git add
        run: |
          git add -A
          ls -la 

      - name: Commit and Push with Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git pull origin main
          git commit -m "ntvtr updated" || echo "nothing to commit"
          git push origin main
