name: ntvtr

on:
  schedule:
    - cron: '*/20 * * * *'  # her 20 dakikada bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "ntvtr bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Execute Python script
        run: python3 ressources/tur/ntv.py

      - name: git add
        run: |
          git add ressources/tur/ntv.m3u8
          git status
          
      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ntv.m3u8 updated" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
          
          
          
          
          
          
          
          
          
          
          
          
