name: ntvtr

on:
  schedule:
    - cron: '16 */20 * * *' # 20 saatte bir çalışır
  workflow_dispatch:         # Elle tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Config Git User
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script
        run: python3 ressources/tur/ntv.py

      - name: Commit & Push Changes
        run: |
          git add ressources/tur/ntv.m3u8
          git commit -m "ntv.m3u8 updated" || echo "nothing to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
          
          
          
          
          
          
          
          
          
          
