name: Encrypted XML Script Runner

on:
  schedule:
    - cron: "0 */12 * * *"  # Her 12 saatte bir
  workflow_dispatch:        # Manuel tetikleme için

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını al
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Uyumlu sürüm

      - name: Gerekli kütüphaneleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install cryptography

      - name: Şifrelenmiş Python scriptini çalıştır
        run: python encrypt_and_compress.py
        
      - name: Betiği çalıştır
        run: |
          python main.py
          
      # - name: .xml dosyasını kontrol et ve sil
        # run: |
          # if [ -f "p1.xml" ]; then
            # echo "p1.xml bulundu. Siliniyor..."
            # rm p1.xml
          # else
            # echo "p1.xml bulunamadı, atlanıyor."
          # fi

      - name: Şifrelenmiş ve sıkıştırılmış çıktıyı yedekle
        uses: actions/upload-artifact@v4
        with:
          name: p1-gz
          path: ressources/xttsearch/p1.xml.gz
