name: p1

on:
  schedule:
    - cron: "0 */24 * * *"  # Her 12 saatte bir çalışır
  workflow_dispatch:         # Elle tetikleme desteği

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Reponun içeriğini klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Python paketlerini yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography

      - name: Betiği çalıştır
        run: python ressources/xttsearch/p1.py

      - name: Oluşturulan dosyaları kontrol et
        run: ls -la ressources/xttsearch

      - name: Commit ve Push işlemleri
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # GitHub Personal Access Token
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}

          CHANGES=0

          if [ -f "ressources/xttsearch/p1.xml" ]; then
            git add ressources/xttsearch/p1.xml
            CHANGES=1
          fi

          if [ -f "ressources/xttsearch/p1.xml.gz" ]; then
            git add ressources/xttsearch/p1.xml.gz
            CHANGES=1
          fi

          if [ "$CHANGES" -eq 1 ]; then
            git commit -m "p1 updated"
            git push origin main
          else
            echo "Değişiklik yok, commit yapılmadı."
          fi

      - name: .xml dosyasını sil
        run: |
          if [ -f "ressources/xttsearch/p1.xml" ]; then
            echo "p1.xml bulundu, siliniyor..."
            rm ressources/xttsearch/p1.xml
          else
            echo "p1.xml zaten yok, atlanıyor."
          fi
